### ISSUE TITLE
[Bug][Jupyter Widget] Map Does Not Display

### ISSUE THREAD

**Issue by suciokhan** [keplergl/kepler.gl#583]
**Describe the bug**
Unable to render KeplerGL map in Jupyter-lab version 0.35.6 and Python 3.6.8. As per the example, I set KeplerGl(height=500) to a variable & call that variable, but neither an image nor error message is displayed.

**To Reproduce**
# Behaves as expected
1. from keplergl import KeplerGl

# Prints URL to user guide
2. map = KeplerGl(height=400) 

 # prints "KeplerGL(). No image displayed
3. map

**Expected behavior**
Expected a basic map to be rendered, as per example found at https://medium.com/vis-gl/introducing-kepler-gl-for-jupyter-f72d41659fbf

**Screenshots**
![image](https://user-images.githubusercontent.com/23055812/60206081-ca2f8c80-9820-11e9-9be6-4d254ee3f2ca.png)

**Environment (please complete the following information):**
 - Python version: 3.6.8
 - keplergl Widget version : 0.1.0a6

**Additional context**
Installation executed via sudo pip3 install keplergl. My friend is experiencing the same error; I do not have his system details however.

**Comment by suciokhan** [comment]
Whoops wrong button

**Comment by dash-alex** [comment]
same problem here, and with some other error info
![image](https://user-images.githubusercontent.com/46229829/60227899-8e013800-98c3-11e9-9de6-61e05b6e40a5.png)

**Comment by heshan0131** [comment]
@dash-alex Are you running it in JupyterLab or Jupyter Notebook?

**Comment by dash-alex** [comment]
> @dash-alex Are you running it in JupyterLab or Jupyter Notebook?

Jupyter Notebook

**Comment by suciokhan** [comment]
> > @dash-alex Are you running it in JupyterLab or Jupyter Notebook?
> 
> Jupyter Notebook

Ah- JupyterLab- good to know. Thanks very much for clarifying.

**Comment by heshan0131** [comment]
Bu @dash-alex you are using Jupyter Notebook and still see console error? Can you describe how you are running it? which version of `ipywidgets` is installed in your environment?

**Comment by kathrine-swe** [comment]
Dropping a plug: It would be really awesome if you guys made the extension for JupyterLab.

**Comment by dash-alex** [comment]
@heshan0131 
```
nbextension:
jupyter nbextension list|grep widget
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: problems found:
        - require?  X rise/main
      - Validating: OK
      - Validating: problems found:
        - require?  X nb_conda
      - Validating: problems found:
        - require?  X bokeh
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
      - Validating: OK
      - Validating: OK
      - Validating: OK
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      jupyter-js-widgets/extension  enabled
ipywidgets:
ipywidgets                7.4.2                      py_0    conda-forge
kepler:
keplergl                  0.1.0a6                  pypi_0    pypi
jupyter version:
jupyter 4.4.0
```
![image](https://user-images.githubusercontent.com/46229829/60313909-5c57a200-9993-11e9-9d87-26cd1e475a00.png)
